# Generated by Django 5.2.8 on 2025-11-17 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(help_text='Contoh: X Kuliner 1', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(help_text='Contoh: GANJIL 2025/2026', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Centang ini untuk semester yang sedang berjalan')),
            ],
        ),
        migrations.CreateModel(
            name='Ekstrakurikuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_eskul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('pelatih', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eskul_diampu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_perwalian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penilaian.kelas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=255)),
                ('nis', models.CharField(help_text='Nomor Induk Siswa', max_length=50, unique=True)),
                ('eskul_yang_diikuti', models.ManyToManyField(related_name='anggota', to='penilaian.ekstrakurikuler')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_di_kelas', to='penilaian.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_kehadiran', models.IntegerField(default=0, help_text='Jumlah kehadiran')),
                ('nilai_keaktifan', models.CharField(choices=[('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup'), ('D', 'Kurang')], default='C', max_length=1)),
                ('kepersertaan_lomba', models.TextField(blank=True, help_text='Catatan keikutsertaan/prestasi lomba', null=True)),
                ('catatan_pelatih', models.TextField(blank=True, null=True)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('eskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_anggota', to='penilaian.ekstrakurikuler')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penilaian_di_semester', to='penilaian.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_eskul', to='penilaian.siswa')),
            ],
        ),
    ]
