# Generated by Django 4.2.11 on 2026-07-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekstrakurikuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_eskul', models.CharField(max_length=100)),
                ('deskripsi_singkat', models.CharField(blank=True, help_text='Deskripsi 1-2 kalimat untuk galeri eskul', max_length=255, null=True)),
                ('deskripsi_panjang', models.TextField(blank=True, help_text='Biodata lengkap eskul (akan tampil di halaman detail)', null=True)),
                ('jadwal_latihan', models.CharField(blank=True, help_text='Contoh: Setiap Jumat, 15:00 - 17:00', max_length=100, null=True)),
                ('lokasi', models.CharField(blank=True, help_text='Contoh: Lapangan Sekolah', max_length=100, null=True)),
                ('prestasi_unggulan', models.TextField(blank=True, help_text='Daftar prestasi, pisahkan dengan baris baru', null=True)),
                ('foto_sampul', models.ImageField(blank=True, help_text='Upload foto sampul (akan di-resize otomatis)', null=True, upload_to='foto_eskul/')),
                ('pelatih', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eskul_diampu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(help_text='Contoh: X Kuliner 1', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tahun', models.CharField(help_text='Contoh: 2025/2026', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Centang untuk tahun ajaran yang sedang berjalan')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=255)),
                ('nis', models.CharField(help_text='Nomor Induk Siswa', max_length=50, unique=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_wa', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_ortu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Orang Tua')),
                ('no_hp_ortu', models.CharField(blank=True, max_length=20, null=True, verbose_name='No HP Orang Tua')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_di_kelas', to='penilaian.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(help_text='Contoh: Ganjil atau Genap', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Centang ini untuk semester yang sedang berjalan')),
                ('tahun_ajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_list', to='penilaian.tahunajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_perwalian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penilaian.kelas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_kehadiran', models.IntegerField(default=0, help_text='Jumlah kehadiran', verbose_name='Jumlah Kehadiran')),
                ('nilai_keaktifan', models.CharField(choices=[('A', 'A - Sangat Baik'), ('B', 'B - Baik'), ('C', 'C - Cukup'), ('D', 'D - Kurang')], default='C', max_length=1)),
                ('kepersertaan_lomba', models.TextField(blank=True, help_text='Catatan keikutsertaan/prestasi lomba', null=True)),
                ('catatan_pelatih', models.TextField(blank=True, null=True)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('eskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_anggota', to='penilaian.ekstrakurikuler')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penilaian_di_semester', to='penilaian.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_eskul', to='penilaian.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=255)),
                ('nis', models.CharField(help_text='Nomor Induk Siswa', max_length=50)),
                ('alasan', models.TextField(blank=True, help_text='Alasan ingin bergabung')),
                ('no_hp_ortu', models.CharField(blank=True, help_text='Nomor HP Orang Tua (Opsional)', max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, help_text='Alamat Domisili (Opsional)', null=True)),
                ('nomor_wa', models.CharField(help_text='Nomor WA yang bisa dihubungi', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Aktif'), ('REJECTED', 'Ditolak'), ('NONAKTIF', 'Nonaktif / Lulus'), ('KELUAR', 'Dikeluarkan / Mengundurkan Diri')], default='PENDING', max_length=15)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('eskul_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='penilaian.ekstrakurikuler')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='penilaian.kelas')),
                ('tahun_ajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar_tahun_ini', to='penilaian.tahunajaran')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Upload foto kegiatan (akan di-resize otomatis)', upload_to='foto_kegiatan/')),
                ('keterangan', models.CharField(blank=True, help_text='Keterangan singkat tentang foto ini', max_length=255, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('eskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri_foto', to='penilaian.ekstrakurikuler')),
            ],
            options={
                'verbose_name': 'Foto Kegiatan Eskul',
                'verbose_name_plural': 'Galeri Foto Eskul',
                'ordering': ['-tanggal_upload'],
            },
        ),
    ]
