# Generated by Django 4.2.11 on 2026-07-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nama_ortu',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='tanggal_lahir',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='tempat_lahir',
        ),
    ]
