# Generated by Django 5.2.8 on 2025-11-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekstrakurikuler',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='ekstrakurikuler',
            name='deskripsi_panjang',
            field=models.TextField(blank=True, help_text='Biodata lengkap eskul (akan tampil di halaman detail)', null=True),
        ),
        migrations.AddField(
            model_name='ekstrakurikuler',
            name='deskripsi_singkat',
            field=models.CharField(blank=True, help_text='Deskripsi 1-2 kalimat untuk galeri eskul', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ekstrakurikuler',
            name='foto_sampul',
            field=models.ImageField(blank=True, help_text='Upload foto sampul (akan di-resize otomatis)', null=True, upload_to='foto_eskul/'),
        ),
        migrations.AddField(
            model_name='ekstrakurikuler',
            name='jadwal_latihan',
            field=models.CharField(blank=True, help_text='Contoh: Setiap Jumat, 15:00 - 17:00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ekstrakurikuler',
            name='lokasi',
            field=models.CharField(blank=True, help_text='Contoh: Lapangan Sekolah', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ekstrakurikuler',
            name='prestasi_unggulan',
            field=models.TextField(blank=True, help_text='Daftar prestasi, pisahkan dengan baris baru', null=True),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='nilai_kehadiran',
            field=models.IntegerField(default=0, help_text='Jumlah kehadiran', verbose_name='Jumlah Kehadiran'),
        ),
    ]
