# Generated by Django 5.2.8 on 2025-11-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0002_remove_ekstrakurikuler_deskripsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Upload foto kegiatan (akan di-resize otomatis)', upload_to='foto_kegiatan/')),
                ('keterangan', models.CharField(blank=True, help_text='Keterangan singkat tentang foto ini', max_length=255, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('eskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri_foto', to='penilaian.ekstrakurikuler')),
            ],
            options={
                'verbose_name': 'Foto Kegiatan Eskul',
                'verbose_name_plural': 'Galeri Foto Eskul',
                'ordering': ['-tanggal_upload'],
            },
        ),
    ]
