# Generated by Django 5.2.8 on 2025-11-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0003_fotoeskul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=255)),
                ('nis', models.CharField(help_text='Nomor Induk Siswa', max_length=50)),
                ('alasan', models.TextField(blank=True, help_text='Alasan ingin bergabung')),
                ('nomor_wa', models.CharField(help_text='Nomor WA yang bisa dihubungi', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('eskul_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='penilaian.ekstrakurikuler')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to='penilaian.kelas')),
            ],
        ),
    ]
