# Generated by Django 5.2.8 on 2025-11-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0004_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='alamat',
            field=models.TextField(blank=True, help_text='Alamat Domisili (Opsional)', null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='no_hp_ortu',
            field=models.CharField(blank=True, help_text='Nomor HP Orang Tua (Opsional)', max_length=20, null=True),
        ),
    ]
